---
- name: Respond to webhook POST
  hosts: localhost
  sources:
    - ansible.eda.pg_listener:
        postgres_params:
          host: 192.168.64.41
          port: 5432
          dbname: awx
          user: postgres
          password: primod123
        channels:
          - ops_alerts
  rules:
    - name: R1 - High CPU usage detected
      condition: true
      action:
        run_job_template:
          name: Investigate_High_CPU
          organization: Default

      

    
