---
- name: Respond to webhook POST
  hosts: localhost
  sources:
    - ansible.eda.pg_listener:
        postgres_params:
          host: 192.168.64.41
          port: 5432
          dbname: awx
          user: postgres
          password: primod123
        channels:
          - ops_alerts
  rules:
    - name: R1 - SELinux is disabled
      condition: event.alert.labels.alertname == "selinux disabled" and event.alert.status == "firing"
      action:
        run_job_template:
          name: Apply baseline
          organization: Default
          job_args:
            limit: "{{ event.meta.hosts }}"

    - name: R2 - SELinux was enabled and now its fixed
      condition: event.alert.labels.alertname == "selinux disabled" and  event.alert.status == "resolved"
      action:
        debug:
          msg: "enabled on: {{ event.meta.hosts }}"

    - name: R3 - High CPU usage detected
      condition: true
      action:
        debug:
      

    
