---
- name: Respond to webhook POST
  hosts: all
  sources:
    - ansible.eda.pg_listener:
        postgres_params:
          host: 192.168.64.41
          port: 5432
          dbname: awx
        channels:
          - ops_alerts
  rules:
    - name: Capture all other events from this source
      condition: event is defined
      action:
        debug:  